### ISSUE TITLE
Move "Vertical Stripes" to "Instrument/Site"

### ISSUE THREAD

**Issue by kadrlica** [pmelchior/des-exp-checker#70] opened 2014-08-31 03:19 UTC
I believe that the vertical stripes are predominantly a feature resulting from electronic noise and should thus be classified under "Instrument/Site".

**Comment by pmelchior** [comment] 2015-10-09 16:29
Duplicate of #76, where more explanation is given. Closing this one.

**Closed by pmelchior** 2015-10-09 16:29 UTC
Labels: duplicate
